#!/bin/sh
set -eu

export PROTONMAIL_USERNAME="${PROTONMAIL_USERNAME:-glama-inspect@example.com}"
export PROTONMAIL_PASSWORD="${PROTONMAIL_PASSWORD:-glama-inspect-password}"
export PROTONMAIL_IMAP_HOST="${PROTONMAIL_IMAP_HOST:-127.0.0.1}"
export PROTONMAIL_IMAP_PORT="${PROTONMAIL_IMAP_PORT:-1143}"
export PROTONMAIL_IMAP_SECURE="${PROTONMAIL_IMAP_SECURE:-false}"
export PROTONMAIL_SMTP_HOST="${PROTONMAIL_SMTP_HOST:-127.0.0.1}"
export PROTONMAIL_SMTP_PORT="${PROTONMAIL_SMTP_PORT:-1025}"
export PROTONMAIL_DATA_DIR="${PROTONMAIL_DATA_DIR:-/tmp/proton-mail-bridge-mcp}"
export PROTONMAIL_AUTO_SYNC="${PROTONMAIL_AUTO_SYNC:-false}"
export PROTONMAIL_STARTUP_SYNC="${PROTONMAIL_STARTUP_SYNC:-false}"
export PROTONMAIL_IDLE_WATCH="${PROTONMAIL_IDLE_WATCH:-false}"
export PROTONMAIL_READ_ONLY="${PROTONMAIL_READ_ONLY:-true}"
export PROTONMAIL_ALLOW_SEND="${PROTONMAIL_ALLOW_SEND:-false}"
export PROTONMAIL_ALLOW_REMOTE_DRAFT_SYNC="${PROTONMAIL_ALLOW_REMOTE_DRAFT_SYNC:-false}"

exec mcp-proxy -- node dist/index.js
